### ISSUE TITLE
Usage example won't run

### ISSUE THREAD

**Issue by sfinam** [love2d-community/splashes#20]
I've tried running the usage example just copying it from readme and it won't run unless I replace dots with colons in update and draw functions

**Comment by s-ol** [comment]
Nice catch, wanna submit a small PR or should I do this, @sfinam?

**Comment by sfinam** [comment]
@s-ol, I'm very new to this so I don't know how to do this =) If you could do this it would be perfect.

**Comment by s-ol** [comment]
@sfinam well, all the more reason to do it a first time :P

You can actually do it right here on github (for a simple one-file-change like this). If you go to the main page of this repository and [open the `README.md`](https://github.com/love2d-community/splashes/blob/master/README.md), you will see a small edit icon (pencil) and can make your changes (use the Preview tab to make sure it looks right).

When you are done you can press the 'Propose Changes' button at the bottom. As the text above explains, github will have created a copy of this repository in your own account (called a fork) and created a Pull-Request proposing to add your change to this original repository too. Also you will be seen as the author of the change in the history of this repository.

If you put the text `Closes #20` in the description box, it will also automatically close this issue (since this issue is #20) when I merge your PR.

**Comment by sfinam** [comment]
OK, I've tried =) Thank you, @s-ol

**Comment by s-ol** [comment]
@sfinam there you go! you can remove your fork of `splashes` now to keep your profile clean. Your contribution will be forever remembered on the contributors page too: https://github.com/love2d-community/splashes/graphs/contributors :smiley:
