### ISSUE TITLE
Running splashes.love in 11.3 does not work

### ISSUE THREAD

**Issue by ghost** [love2d-community/splashes#25]
it runs but it is all in white

**Comment by kulothunganug** [comment]
`splashes` is just amazing, it's working on LOVE 11.3 nicely.
Please close this issue and maintainer should change the version tag (on [README.md](https://github.com/love2d-community/splashes/blob/master/README.md)) from 0.10.1 to 11.3

**Comment by JustASpeedrunner** [comment]
**NOTE: This issue IS fixed in the repo, however the releases have not been updated to do so. You can git clone the repo OR use the .love file provided below and you will no longer experience the issue.**

This error is due to the change to using RGB values within the range of 0-1 in 11.0 compared to versions prior where it uses 0-255. I changed the numbers from, for example, 255 to 255/255 which makes the value fit on the scale of 0-1. You can download an [updated version of the .love file here.](https://cdn.discordapp.com/attachments/853801043301498920/938592106912563230/splashes.love)
Below is the list of changes I made to each file.

**Changes to /main.lua on line 34**
Old:
`love.graphics.setColor(255, 255, 255)`
New:
`love.graphics.setColor(1,1,1)`

**Changes to /o-ten-one/init.lua on lines 30-36**
Old:
```
local colors = {
  bg =     {108, 190, 228},
  white =  {255, 255, 255},
  blue =   { 39, 170, 225},
  pink =   {231,  74, 153},
  shadow = {0, 0, 0, 255/3}
}
```
New:
```
local colors = {
  bg =     {108/255, 190/255, 228/255},
  white =  {255/255, 255/255, 255/255},
  blue =   { 39/255, 170/255, 225/255},
  pink =   {231/255,  74/255, 153/255},
  shadow = {0, 0, 0, (255/3)/255}
}
```
